### PR TITLE
Refactor best practice

### PR DESCRIPTION
**Pull request by TadesseDev**
## Change introduced 😎
---
- Refactor My own Ruby code after gaining new knowledge. :heavy_check_mark: 
- Apply Ruby best practices and language style guides in code. :heavy_check_mark: 
- Apply YAGNI, KISS, and DRY rules and Ruby style guide. :heavy_check_mark: 
- Follow SOLID principles. :heavy_check_mark:

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @Tadesse-Alemayehu @marurevi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Git flow 
✔️ Following the SOLID design principles
✔️ Professional PR

## Required Changes ♻️

- [ ] In `create_person` method You should use the `Single responsibility principle` by putting the case `input` into a private method and use that method in create person that will make the code looks cleaner and also follow the S from Solid design principles
Screen Shot 2022-07-26 at 14 38 00


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
@youmari thanks for the review. we will make sure to make the changes.

**Review by RolandM99 — APPROVED** [review]
<h1>Status: Approve 🥇 ✔</h1>

### Hello Team, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
Thanks, @RolandM99. Appreciate it.

**Pull request merged**
