### PR TITLE
OOP school library: add basic UI

### PR DESCRIPTION
**Pull request by TadesseDev**
## Change introduced 😎
---
- Build interactive console apps.✔
- Run a program using the command line.✔
- Create a `app.rb` file.✔
- Create my `main.rb` file that serve as my console app entry-point. ✔

### CODE REVIEW

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Tadesse-Alemayehu,

Good job so far!
✔️ App works as expected
✔️ The `main.rb` file serves as entry point
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] **Kindly edit your README to be descriptive of this project**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
Thank you @TedLivist, I'll update my readme before the next review request.

**Review by uwadonat — APPROVED** [review]
## Hi @Tadesse-Alemayehu,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- The project works as expected ✔️
- Professional readme file ✔️
good-job-awesome

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by TadesseDev** [comment]
Thank you @uwadonat, Nice to have a confirmation on the project requirements.

**Pull request merged**
