### PR TITLE
Preserve data

### PR DESCRIPTION
**Pull request by joshuaoivie**
Dear Code Reviewer,

This pull request contains the following changes.

- Add process file
- Add support for JSON
- Load books, people, and rentals data from JSON files upon application start
- Save books, people, and rentals data to JSON files upon application end
- Refactor main.rb and app.rb
- Fix linter errors

Warm Regards,
Joshua Ivie

### CODE REVIEW

**Review by EricMbouwe — CHANGES_REQUESTED** [review]
Hi @joshuaivie, 

Good job so far 🔥!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🔥🎉
- ⚡You implemented the save method
- ⚡You set the write into files
- ⚡Linters ok
## Required Changes ♻️
_Check the comments under the review._
- [ ] The project is not running on startup because of a read file function which is not succeeding. Let's fix that

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
Thank you @EricMbouwe we will make sure to fix that before the next review request.

**Comment by TadesseDev** [comment]
Dear @EricMbouwe, I was testing the project on my local machine and it seems everything is working. I even delete the `.Json` files and try again. I have attached a link for the video of the project. [video link](https://www.loom.com/share/1d8b3acd14c042ebbef5347637bc8796)

**Review by bimbolabuari — COMMENTED** [review]
Hello @joshuaivie & @Tadesse-Alemayehu  👋,

_This is an additional review as a result of the second opinion request._

- In order to give a clear understanding, Your app works fine, but the JSON error handling in your `proccess_file.rb` is catching an error before the app starts running. It is a nice practice to use an error handler, However, the mistake is from the `read_json` method.

- Kindly make the changes requested by the previous code reviewer, and re-submit on your dashboard for approval

Keep rocking 🚀!

**Comment by TadesseDev** [comment]
Thanks, @bimbolabuari. we will make the changes now.

**Review by DeliceLydia — APPROVED** [review]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
Thanks, @DeliceLydia. Nice to have your review.🙏🏼

**Pull request merged**
